#docker-compose for Dinly schoolproject
version: '3.7'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: dinly.es
    environment:
      - discovery.type=single-node
    volumes:
      - es.data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticnet

  kib:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: dinly.kib
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - elasticnet

volumes:
  es.data:
    driver: local

networks:
  elasticnet:
    driver: bridge