version: "3.3"
services:
    web:
        image: "jrichtsfeld/myrecipebackend"
        ports:
            - "8000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
            - StaticFiles:ImageBasePath=RecipeImages
            - ConnectionStrings:DefaultConnection=Data Source=db;Initial Catalog=MyRecipe;User=sa;Password=Al26Dnas!123;
            - Jwt:Key=YVBy0OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SBM=
            - Jwt:Issuer=http://185.239.238.179
            - Jwt:Audience=http://185.239.238.179
            - Jwt:RefreshProvider=RefTokenProvider
            - SpaLinks:ResetPasswordBaseLink=http://185.239.238.179/confirmreset
            - SpaLinks:ResetEmailBaseLink=http://185.239.238.179/confirmemailchange
            - SendGridUser=MyRecipe
            - SendGridKey=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
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            - SA_PASSWORD=Al26Dnas!123
            - ACCEPT_EULA=Y
